development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: password
  database: receta_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: password
  database: receta_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: password
  database: receta
  pool: 5
